name: Update Clash Config

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点运行一次（可根据需求修改时间）

  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 拉取仓库内容

    - name: Download ACL4SSR rules
      run: |
        mkdir -p acl4ssr
        wget -O acl4ssr/acl4ssr.yaml https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full.yaml

    - name: Merge custom nodes with ACL4SSR rules
      run: |
        # 创建合并文件夹
        mkdir -p merged

        # 将自定义节点合并到规则文件中
        cat custom-nodes.yaml acl4ssr/acl4ssr.yaml > merged/merged-config.yaml

    - name: Commit and push updated config
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # 检查合并文件是否更改
        if [[ `git status --porcelain` ]]; then
          git add merged/merged-config.yaml
          git commit -m "Update merged config $(date +'%Y-%m-%d')"
          git push
        fi
